theme:
  background: "#1e1e2ef0"
  divider: "#3c3c50"
  primary: "#cdd6f4"
  secondary: "#a0a0b4"
  selection: "#6496e6c8"
  # font: ""

desktop:
  enabled: true

code:
  enabled: false
  dir: ~/code
  command: "code %s"

folders:
  enabled: false

arch:
  enabled: false

calc:
  enabled: false

search:
  enabled: false
  providers:
    - name: kagi
      url: "https://kagi.com/search?q=%s"
      always_include: true
    - name: google
      url: "https://www.google.com/search?q=%s"
      always_include: false
    - name: letterboxd
      aliases: ["lb"]
      url: "https://letterboxd.com/search/%s/"
      always_include: false
